# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EWlfyFeXCLTs4NlXbUUHhA48JRX3j8R_
"""

import streamlit as st

# Define scoring functions for each category
def calculate_health_score(chronic_condition, checkups, medication):
    score = 0
    if chronic_condition.lower() == 'no':
        score += 10
    if checkups == 'Regularly':
        score += 10
    if medication.lower() == 'no':
        score += 10
    return score

def calculate_lifestyle_score(sleep_hours, smoking, alcohol, work_life_balance):
    score = 0
    if sleep_hours >= 7:
        score += 10
    if smoking.lower() == 'no':
        score += 10
    if alcohol.lower() == 'no':
        score += 10
    if work_life_balance == 'Excellent':
        score += 10
    return score

def calculate_diet_score(fruit_veg_servings, processed_food, hydration):
    score = 0
    if fruit_veg_servings >= 5:
        score += 10
    if processed_food == 'Never':
        score += 10
    if hydration >= 8:
        score += 10
    return score

def calculate_exercise_score(exercise_days, exercise_type, motivation):
    score = 0
    if exercise_days >= 3:
        score += 10
    if exercise_type in ['Cardio', 'Strength Training', 'Yoga']:
        score += 10
    if motivation >= 70:
        score += 10
    return score

def calculate_stress_score(stress_frequency, stress_management_effectiveness):
    score = 0
    if stress_frequency == 'Rarely':
        score += 10
    if stress_management_effectiveness >= 70:
        score += 10
    return score

def wellness_score_calculator():
    st.title("Conversational Wellness Score Calculator")

    # Health
    st.write("### Health")
    chronic_condition = st.selectbox("Do you have any chronic health conditions?", ["Yes", "No"])
    checkups = st.selectbox("How often do you visit a doctor for a check-up?", ["Regularly", "Occasionally", "Rarely"])
    medication = st.selectbox("Are you currently taking any prescription medication?", ["Yes", "No"])

    # Lifestyle
    st.write("### Lifestyle")
    sleep_hours = st.slider("On average, how many hours of sleep do you get per night?", 1, 24)
    smoking = st.selectbox("Do you smoke or use tobacco products regularly?", ["Yes", "No"])
    alcohol = st.selectbox("Do you consume alcohol regularly?", ["Yes", "No"])
    work_life_balance = st.selectbox("How would you rate your work-life balance?", ["Excellent", "Good", "Fair", "Poor"])

    # Diet
    st.write("### Diet")
    fruit_veg_servings = st.slider("How many servings of fruits and vegetables do you consume daily?", 0, 10)
    processed_food = st.selectbox("How often do you consume processed or fast food?", ["Daily", "Weekly", "Rarely", "Never"])
    hydration = st.slider("How many glasses of water do you drink daily?", 0, 20)

    # Exercise
    st.write("### Exercise")
    exercise_days = st.slider("How many days per week do you engage in physical exercise?", 0, 7)
    exercise_type = st.selectbox("What type of exercise do you engage in regularly?", ["Cardio", "Strength Training", "Yoga", "Sports", "None"])
    motivation = st.slider("How motivated are you to exercise regularly?", 1, 100)

    # Stress
    st.write("### Stress")
    stress_frequency = st.selectbox("How often do you feel stressed?", ["Often", "Occasionally", "Rarely"])
    stress_management_effectiveness = st.slider("How effective are your stress management techniques?", 1, 100)

    # Calculate and display the score
    if st.button("Calculate Wellness Score"):
        total_score = 0
        total_score += calculate_health_score(chronic_condition, checkups, medication)
        total_score += calculate_lifestyle_score(sleep_hours, smoking, alcohol, work_life_balance)
        total_score += calculate_diet_score(fruit_veg_servings, processed_food, hydration)
        total_score += calculate_exercise_score(exercise_days, exercise_type, motivation)
        total_score += calculate_stress_score(stress_frequency, stress_management_effectiveness)

        st.write(f"### Your Wellness Score is: {total_score}/100")

        if total_score > 80:
            st.success("Based on your responses, we recommend you enroll in our advanced wellness program.")
        elif total_score < 60:
            st.warning("It seems like you could benefit from our basic health program. Let's start there!")
        else:
            st.info("You might want to consult with one of our wellness coaches to fine-tune your health plan.")

        st.write("Thank you for participating in the Wellness Score Calculator!")

if __name__ == "__main__":
    wellness_score_calculator()

