# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EWlfyFeXCLTs4NlXbUUHhA48JRX3j8R_
"""

import streamlit as st

# Define scoring functions for each category

def calculate_health_score(chronic_condition, checkups):
    score = 0
    if not chronic_condition:
        score += 10
    if checkups == 'regularly':
        score += 10
    return score

def calculate_lifestyle_score(sleep_hours, smoking_drinking):
    score = 0
    if sleep_hours >= 7:
        score += 10
    if not smoking_drinking:
        score += 10
    return score

def calculate_diet_score(fruit_veg_servings, processed_food):
    score = 0
    if fruit_veg_servings >= 5:
        score += 10
    if not processed_food:
        score += 10
    return score

def calculate_exercise_score(exercise_days, exercise_type):
    score = 0
    if exercise_days >= 3:
        score += 10
    if exercise_type in ['cardio', 'strength', 'yoga']:
        score += 10
    return score

def calculate_stress_score(stress_frequency, stress_management):
    score = 0
    if stress_frequency == 'rarely':
        score += 10
    if stress_management:
        score += 10
    return score

# Define the Streamlit app

def wellness_score_calculator():
    st.title("Wellness Score Calculator")

    # Health
    chronic_condition = st.radio("Do you have any chronic health conditions?", options=['Yes', 'No']) == 'No'
    checkups = st.selectbox("How often do you visit a doctor for a check-up?", options=['Regularly', 'Occasionally', 'Rarely'])

    # Lifestyle
    sleep_hours = st.slider("How many hours of sleep do you get on average per night?", min_value=0, max_value=12, value=7)
    smoking_drinking = st.radio("Do you smoke or consume alcohol regularly?", options=['Yes', 'No']) == 'No'

    # Diet
    fruit_veg_servings = st.slider("How many servings of fruits and vegetables do you eat daily?", min_value=0, max_value=10, value=5)
    processed_food = st.radio("Do you consume processed or fast food regularly?", options=['Yes', 'No']) == 'No'

    # Exercise
    exercise_days = st.slider("How many days per week do you exercise?", min_value=0, max_value=7, value=3)
    exercise_type = st.selectbox("What type of exercise do you engage in?", options=['Cardio', 'Strength', 'Yoga', 'Other'])

    # Stress
    stress_frequency = st.selectbox("How often do you feel stressed?", options=['Often', 'Occasionally', 'Rarely'])
    stress_management = st.radio("Do you practice any stress management techniques?", options=['Yes', 'No']) == 'Yes'

    # Calculate scores
    total_score = 0
    total_score += calculate_health_score(chronic_condition, checkups)
    total_score += calculate_lifestyle_score(sleep_hours, smoking_drinking)
    total_score += calculate_diet_score(fruit_veg_servings, processed_food)
    total_score += calculate_exercise_score(exercise_days, exercise_type.lower())
    total_score += calculate_stress_score(stress_frequency.lower(), stress_management)

    # Display the score and recommendation
    st.write(f"### Your Wellness Score is: {total_score}/100")

    if total_score > 80:
        st.success("We recommend you enroll in our advanced wellness program.")
    elif total_score < 60:
        st.warning("We suggest you start with our basic health program.")
    else:
        st.info("We recommend a consultation with one of our wellness coaches.")

    st.write("Thank you for using the Wellness Score Calculator!")

if __name__ == "__main__":
    wellness_score_calculator()